### ISSUE TITLE
Error in Line 75 (windows) - creating the folder

### ISSUE THREAD

**Issue by Surfer2010** [RacsoRhodes/travelpoints#5]
in order to get this mod to work in windows, you need to manual create a folder named: travelpoints_tables in the world-folder of your game-world.

Second you also need to delete line 75
--os.execute("mkdir \"" .. travelpoints.travelpoints_tables .. "\"")
otherwise it will still crash on windows systems

**Comment by RacsoRhodes** [comment]
Github user "ritschwumm" pointed out the use of minetest.mkdir() instead of the now deprecated os.execute().

Thanks for bringing this to my attention, the corrections have been made.
